version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

  server:
    build: 
      context: ./server
      dockerfile: Dockerfile
    container_name: chat-server
    restart: always
    ports:
      - "3001:3000"
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - PORT=3000
      - MONGODB_URI=mongodb://mongodb:27017/voicechat
      - JWT_SECRET=your-super-secret-key-change-this-in-production
      - UPLOADS_DIR=uploads
    depends_on:
      - mongodb
    networks:
      - app-network

volumes:
  mongodb_data:
    driver: local

networks:
  app-network:
    driver: bridge 